// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: messenger.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RoboMessenger_ChatStream_FullMethodName   = "/robo_claw.RoboMessenger/ChatStream"
	RoboMessenger_SendCommand_FullMethodName  = "/robo_claw.RoboMessenger/SendCommand"
	RoboMessenger_UploadFile_FullMethodName   = "/robo_claw.RoboMessenger/UploadFile"
	RoboMessenger_DownloadFile_FullMethodName = "/robo_claw.RoboMessenger/DownloadFile"
)

// RoboMessengerClient is the client API for RoboMessenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoboMessengerClient interface {
	// 양방향 스트리밍 대화: 사용자와 로봇이 실시간으로 메시지를 주고받음
	ChatStream(ctx context.Context, opts ...grpc.CallOption) (RoboMessenger_ChatStreamClient, error)
	// 단발성 명령 전송 및 결과 수신
	SendCommand(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*CommandResponse, error)
	// 파일 업로드 스트리밍
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (RoboMessenger_UploadFileClient, error)
	// 파일 다운로드 스트리밍
	DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (RoboMessenger_DownloadFileClient, error)
}

type roboMessengerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoboMessengerClient(cc grpc.ClientConnInterface) RoboMessengerClient {
	return &roboMessengerClient{cc}
}

func (c *roboMessengerClient) ChatStream(ctx context.Context, opts ...grpc.CallOption) (RoboMessenger_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoboMessenger_ServiceDesc.Streams[0], RoboMessenger_ChatStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &roboMessengerChatStreamClient{stream}
	return x, nil
}

type RoboMessenger_ChatStreamClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type roboMessengerChatStreamClient struct {
	grpc.ClientStream
}

func (x *roboMessengerChatStreamClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roboMessengerChatStreamClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roboMessengerClient) SendCommand(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, RoboMessenger_SendCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roboMessengerClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (RoboMessenger_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoboMessenger_ServiceDesc.Streams[1], RoboMessenger_UploadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &roboMessengerUploadFileClient{stream}
	return x, nil
}

type RoboMessenger_UploadFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type roboMessengerUploadFileClient struct {
	grpc.ClientStream
}

func (x *roboMessengerUploadFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roboMessengerUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roboMessengerClient) DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (RoboMessenger_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoboMessenger_ServiceDesc.Streams[2], RoboMessenger_DownloadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &roboMessengerDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoboMessenger_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type roboMessengerDownloadFileClient struct {
	grpc.ClientStream
}

func (x *roboMessengerDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoboMessengerServer is the server API for RoboMessenger service.
// All implementations must embed UnimplementedRoboMessengerServer
// for forward compatibility
type RoboMessengerServer interface {
	// 양방향 스트리밍 대화: 사용자와 로봇이 실시간으로 메시지를 주고받음
	ChatStream(RoboMessenger_ChatStreamServer) error
	// 단발성 명령 전송 및 결과 수신
	SendCommand(context.Context, *ChatMessage) (*CommandResponse, error)
	// 파일 업로드 스트리밍
	UploadFile(RoboMessenger_UploadFileServer) error
	// 파일 다운로드 스트리밍
	DownloadFile(*DownloadRequest, RoboMessenger_DownloadFileServer) error
	mustEmbedUnimplementedRoboMessengerServer()
}

// UnimplementedRoboMessengerServer must be embedded to have forward compatible implementations.
type UnimplementedRoboMessengerServer struct {
}

func (UnimplementedRoboMessengerServer) ChatStream(RoboMessenger_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedRoboMessengerServer) SendCommand(context.Context, *ChatMessage) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedRoboMessengerServer) UploadFile(RoboMessenger_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedRoboMessengerServer) DownloadFile(*DownloadRequest, RoboMessenger_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedRoboMessengerServer) mustEmbedUnimplementedRoboMessengerServer() {}

// UnsafeRoboMessengerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoboMessengerServer will
// result in compilation errors.
type UnsafeRoboMessengerServer interface {
	mustEmbedUnimplementedRoboMessengerServer()
}

func RegisterRoboMessengerServer(s grpc.ServiceRegistrar, srv RoboMessengerServer) {
	s.RegisterService(&RoboMessenger_ServiceDesc, srv)
}

func _RoboMessenger_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoboMessengerServer).ChatStream(&roboMessengerChatStreamServer{stream})
}

type RoboMessenger_ChatStreamServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type roboMessengerChatStreamServer struct {
	grpc.ServerStream
}

func (x *roboMessengerChatStreamServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roboMessengerChatStreamServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RoboMessenger_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoboMessengerServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoboMessenger_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoboMessengerServer).SendCommand(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoboMessenger_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoboMessengerServer).UploadFile(&roboMessengerUploadFileServer{stream})
}

type RoboMessenger_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type roboMessengerUploadFileServer struct {
	grpc.ServerStream
}

func (x *roboMessengerUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roboMessengerUploadFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RoboMessenger_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoboMessengerServer).DownloadFile(m, &roboMessengerDownloadFileServer{stream})
}

type RoboMessenger_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type roboMessengerDownloadFileServer struct {
	grpc.ServerStream
}

func (x *roboMessengerDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

// RoboMessenger_ServiceDesc is the grpc.ServiceDesc for RoboMessenger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoboMessenger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robo_claw.RoboMessenger",
	HandlerType: (*RoboMessengerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _RoboMessenger_SendCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _RoboMessenger_ChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _RoboMessenger_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _RoboMessenger_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messenger.proto",
}
