// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: robo.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RosGrpc_Ping_FullMethodName                      = "/ros_grpc.RosGrpc/Ping"
	RosGrpc_GetRobotInfo_FullMethodName              = "/ros_grpc.RosGrpc/GetRobotInfo"
	RosGrpc_GetRobotCameraImage_FullMethodName       = "/ros_grpc.RosGrpc/GetRobotCameraImage"
	RosGrpc_GetRobotCameraImageStream_FullMethodName = "/ros_grpc.RosGrpc/GetRobotCameraImageStream"
	RosGrpc_GetCurrentRobotPose_FullMethodName       = "/ros_grpc.RosGrpc/GetCurrentRobotPose"
	RosGrpc_GetCurrentRobotBattery_FullMethodName    = "/ros_grpc.RosGrpc/GetCurrentRobotBattery"
	RosGrpc_GetLatestRobotHistory_FullMethodName     = "/ros_grpc.RosGrpc/GetLatestRobotHistory"
	RosGrpc_GetRobotHistoryList_FullMethodName       = "/ros_grpc.RosGrpc/GetRobotHistoryList"
	RosGrpc_NavigateToPose_FullMethodName            = "/ros_grpc.RosGrpc/NavigateToPose"
	RosGrpc_EmergencyStop_FullMethodName             = "/ros_grpc.RosGrpc/EmergencyStop"
	RosGrpc_FollowWaypoints_FullMethodName           = "/ros_grpc.RosGrpc/FollowWaypoints"
	RosGrpc_SetInitialPose_FullMethodName            = "/ros_grpc.RosGrpc/SetInitialPose"
	RosGrpc_GetRobotMap_FullMethodName               = "/ros_grpc.RosGrpc/GetRobotMap"
	RosGrpc_ControlJoints_FullMethodName             = "/ros_grpc.RosGrpc/ControlJoints"
	RosGrpc_GetRobotStatus_FullMethodName            = "/ros_grpc.RosGrpc/GetRobotStatus"
	RosGrpc_GetRobotStatusStream_FullMethodName      = "/ros_grpc.RosGrpc/GetRobotStatusStream"
	RosGrpc_ExecuteROSCommand_FullMethodName         = "/ros_grpc.RosGrpc/ExecuteROSCommand"
	RosGrpc_ExecuteROSCommandStream_FullMethodName   = "/ros_grpc.RosGrpc/ExecuteROSCommandStream"
	RosGrpc_UploadFile_FullMethodName                = "/ros_grpc.RosGrpc/UploadFile"
	RosGrpc_DownloadFile_FullMethodName              = "/ros_grpc.RosGrpc/DownloadFile"
)

// RosGrpcClient is the client API for RosGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RosGrpcClient interface {
	// Ping service
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Pong, error)
	// Robot information service
	GetRobotInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Robot, error)
	// Robot camera image service
	GetRobotCameraImage(ctx context.Context, in *CameraRequest, opts ...grpc.CallOption) (*RobotCameraImage, error)
	// Robot camera image stream service
	GetRobotCameraImageStream(ctx context.Context, in *CameraRequest, opts ...grpc.CallOption) (RosGrpc_GetRobotCameraImageStreamClient, error)
	// Robot pose service
	GetCurrentRobotPose(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotPose, error)
	// Robot battery service
	GetCurrentRobotBattery(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotBattery, error)
	// Robot history service - REFACTORED
	GetLatestRobotHistory(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotHistory, error)
	// Robot history list service - REFACTORED
	GetRobotHistoryList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotHistoryList, error)
	// Navigate to pose service
	NavigateToPose(ctx context.Context, in *NavigationGoal, opts ...grpc.CallOption) (*ActionResult, error)
	// Emergency stop service
	EmergencyStop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// Follow waypoints service
	FollowWaypoints(ctx context.Context, in *WaypointList, opts ...grpc.CallOption) (*ActionResult, error)
	// Set initial pose service
	SetInitialPose(ctx context.Context, in *RobotPose, opts ...grpc.CallOption) (*ActionResult, error)
	// Get robot map service
	GetRobotMap(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*OccupancyGrid, error)
	// Control joints service
	ControlJoints(ctx context.Context, in *JointControlRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// Get robot status service
	GetRobotStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotStatus, error)
	// Get robot status stream service
	GetRobotStatusStream(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (RosGrpc_GetRobotStatusStreamClient, error)
	// Execute ROS command service
	ExecuteROSCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Execute ROS command stream service
	ExecuteROSCommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (RosGrpc_ExecuteROSCommandStreamClient, error)
	// Upload file service
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (RosGrpc_UploadFileClient, error)
	// Download file service
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (RosGrpc_DownloadFileClient, error)
}

type rosGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRosGrpcClient(cc grpc.ClientConnInterface) RosGrpcClient {
	return &rosGrpcClient{cc}
}

func (c *rosGrpcClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, RosGrpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Robot, error) {
	out := new(Robot)
	err := c.cc.Invoke(ctx, RosGrpc_GetRobotInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotCameraImage(ctx context.Context, in *CameraRequest, opts ...grpc.CallOption) (*RobotCameraImage, error) {
	out := new(RobotCameraImage)
	err := c.cc.Invoke(ctx, RosGrpc_GetRobotCameraImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotCameraImageStream(ctx context.Context, in *CameraRequest, opts ...grpc.CallOption) (RosGrpc_GetRobotCameraImageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RosGrpc_ServiceDesc.Streams[0], RosGrpc_GetRobotCameraImageStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rosGrpcGetRobotCameraImageStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RosGrpc_GetRobotCameraImageStreamClient interface {
	Recv() (*RobotCameraImage, error)
	grpc.ClientStream
}

type rosGrpcGetRobotCameraImageStreamClient struct {
	grpc.ClientStream
}

func (x *rosGrpcGetRobotCameraImageStreamClient) Recv() (*RobotCameraImage, error) {
	m := new(RobotCameraImage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rosGrpcClient) GetCurrentRobotPose(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotPose, error) {
	out := new(RobotPose)
	err := c.cc.Invoke(ctx, RosGrpc_GetCurrentRobotPose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetCurrentRobotBattery(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotBattery, error) {
	out := new(RobotBattery)
	err := c.cc.Invoke(ctx, RosGrpc_GetCurrentRobotBattery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetLatestRobotHistory(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotHistory, error) {
	out := new(RobotHistory)
	err := c.cc.Invoke(ctx, RosGrpc_GetLatestRobotHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotHistoryList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotHistoryList, error) {
	out := new(RobotHistoryList)
	err := c.cc.Invoke(ctx, RosGrpc_GetRobotHistoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) NavigateToPose(ctx context.Context, in *NavigationGoal, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, RosGrpc_NavigateToPose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) EmergencyStop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, RosGrpc_EmergencyStop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) FollowWaypoints(ctx context.Context, in *WaypointList, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, RosGrpc_FollowWaypoints_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) SetInitialPose(ctx context.Context, in *RobotPose, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, RosGrpc_SetInitialPose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotMap(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*OccupancyGrid, error) {
	out := new(OccupancyGrid)
	err := c.cc.Invoke(ctx, RosGrpc_GetRobotMap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) ControlJoints(ctx context.Context, in *JointControlRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, RosGrpc_ControlJoints_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RobotStatus, error) {
	out := new(RobotStatus)
	err := c.cc.Invoke(ctx, RosGrpc_GetRobotStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) GetRobotStatusStream(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (RosGrpc_GetRobotStatusStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RosGrpc_ServiceDesc.Streams[1], RosGrpc_GetRobotStatusStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rosGrpcGetRobotStatusStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RosGrpc_GetRobotStatusStreamClient interface {
	Recv() (*RobotStatus, error)
	grpc.ClientStream
}

type rosGrpcGetRobotStatusStreamClient struct {
	grpc.ClientStream
}

func (x *rosGrpcGetRobotStatusStreamClient) Recv() (*RobotStatus, error) {
	m := new(RobotStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rosGrpcClient) ExecuteROSCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, RosGrpc_ExecuteROSCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosGrpcClient) ExecuteROSCommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (RosGrpc_ExecuteROSCommandStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RosGrpc_ServiceDesc.Streams[2], RosGrpc_ExecuteROSCommandStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rosGrpcExecuteROSCommandStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RosGrpc_ExecuteROSCommandStreamClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type rosGrpcExecuteROSCommandStreamClient struct {
	grpc.ClientStream
}

func (x *rosGrpcExecuteROSCommandStreamClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rosGrpcClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (RosGrpc_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &RosGrpc_ServiceDesc.Streams[3], RosGrpc_UploadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rosGrpcUploadFileClient{stream}
	return x, nil
}

type RosGrpc_UploadFileClient interface {
	Send(*UploadFileRequest) error
	CloseAndRecv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type rosGrpcUploadFileClient struct {
	grpc.ClientStream
}

func (x *rosGrpcUploadFileClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rosGrpcUploadFileClient) CloseAndRecv() (*UploadFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rosGrpcClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (RosGrpc_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &RosGrpc_ServiceDesc.Streams[4], RosGrpc_DownloadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rosGrpcDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RosGrpc_DownloadFileClient interface {
	Recv() (*DownloadFileResponse, error)
	grpc.ClientStream
}

type rosGrpcDownloadFileClient struct {
	grpc.ClientStream
}

func (x *rosGrpcDownloadFileClient) Recv() (*DownloadFileResponse, error) {
	m := new(DownloadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RosGrpcServer is the server API for RosGrpc service.
// All implementations must embed UnimplementedRosGrpcServer
// for forward compatibility
type RosGrpcServer interface {
	// Ping service
	Ping(context.Context, *PingRequest) (*Pong, error)
	// Robot information service
	GetRobotInfo(context.Context, *EmptyRequest) (*Robot, error)
	// Robot camera image service
	GetRobotCameraImage(context.Context, *CameraRequest) (*RobotCameraImage, error)
	// Robot camera image stream service
	GetRobotCameraImageStream(*CameraRequest, RosGrpc_GetRobotCameraImageStreamServer) error
	// Robot pose service
	GetCurrentRobotPose(context.Context, *EmptyRequest) (*RobotPose, error)
	// Robot battery service
	GetCurrentRobotBattery(context.Context, *EmptyRequest) (*RobotBattery, error)
	// Robot history service - REFACTORED
	GetLatestRobotHistory(context.Context, *EmptyRequest) (*RobotHistory, error)
	// Robot history list service - REFACTORED
	GetRobotHistoryList(context.Context, *EmptyRequest) (*RobotHistoryList, error)
	// Navigate to pose service
	NavigateToPose(context.Context, *NavigationGoal) (*ActionResult, error)
	// Emergency stop service
	EmergencyStop(context.Context, *EmptyRequest) (*ActionResult, error)
	// Follow waypoints service
	FollowWaypoints(context.Context, *WaypointList) (*ActionResult, error)
	// Set initial pose service
	SetInitialPose(context.Context, *RobotPose) (*ActionResult, error)
	// Get robot map service
	GetRobotMap(context.Context, *EmptyRequest) (*OccupancyGrid, error)
	// Control joints service
	ControlJoints(context.Context, *JointControlRequest) (*ActionResult, error)
	// Get robot status service
	GetRobotStatus(context.Context, *EmptyRequest) (*RobotStatus, error)
	// Get robot status stream service
	GetRobotStatusStream(*EmptyRequest, RosGrpc_GetRobotStatusStreamServer) error
	// Execute ROS command service
	ExecuteROSCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	// Execute ROS command stream service
	ExecuteROSCommandStream(*CommandRequest, RosGrpc_ExecuteROSCommandStreamServer) error
	// Upload file service
	UploadFile(RosGrpc_UploadFileServer) error
	// Download file service
	DownloadFile(*DownloadFileRequest, RosGrpc_DownloadFileServer) error
	mustEmbedUnimplementedRosGrpcServer()
}

// UnimplementedRosGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedRosGrpcServer struct {
}

func (UnimplementedRosGrpcServer) Ping(context.Context, *PingRequest) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotInfo(context.Context, *EmptyRequest) (*Robot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotInfo not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotCameraImage(context.Context, *CameraRequest) (*RobotCameraImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotCameraImage not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotCameraImageStream(*CameraRequest, RosGrpc_GetRobotCameraImageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRobotCameraImageStream not implemented")
}
func (UnimplementedRosGrpcServer) GetCurrentRobotPose(context.Context, *EmptyRequest) (*RobotPose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentRobotPose not implemented")
}
func (UnimplementedRosGrpcServer) GetCurrentRobotBattery(context.Context, *EmptyRequest) (*RobotBattery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentRobotBattery not implemented")
}
func (UnimplementedRosGrpcServer) GetLatestRobotHistory(context.Context, *EmptyRequest) (*RobotHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRobotHistory not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotHistoryList(context.Context, *EmptyRequest) (*RobotHistoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotHistoryList not implemented")
}
func (UnimplementedRosGrpcServer) NavigateToPose(context.Context, *NavigationGoal) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NavigateToPose not implemented")
}
func (UnimplementedRosGrpcServer) EmergencyStop(context.Context, *EmptyRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyStop not implemented")
}
func (UnimplementedRosGrpcServer) FollowWaypoints(context.Context, *WaypointList) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowWaypoints not implemented")
}
func (UnimplementedRosGrpcServer) SetInitialPose(context.Context, *RobotPose) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInitialPose not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotMap(context.Context, *EmptyRequest) (*OccupancyGrid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotMap not implemented")
}
func (UnimplementedRosGrpcServer) ControlJoints(context.Context, *JointControlRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlJoints not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotStatus(context.Context, *EmptyRequest) (*RobotStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotStatus not implemented")
}
func (UnimplementedRosGrpcServer) GetRobotStatusStream(*EmptyRequest, RosGrpc_GetRobotStatusStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRobotStatusStream not implemented")
}
func (UnimplementedRosGrpcServer) ExecuteROSCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteROSCommand not implemented")
}
func (UnimplementedRosGrpcServer) ExecuteROSCommandStream(*CommandRequest, RosGrpc_ExecuteROSCommandStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteROSCommandStream not implemented")
}
func (UnimplementedRosGrpcServer) UploadFile(RosGrpc_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedRosGrpcServer) DownloadFile(*DownloadFileRequest, RosGrpc_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedRosGrpcServer) mustEmbedUnimplementedRosGrpcServer() {}

// UnsafeRosGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RosGrpcServer will
// result in compilation errors.
type UnsafeRosGrpcServer interface {
	mustEmbedUnimplementedRosGrpcServer()
}

func RegisterRosGrpcServer(s grpc.ServiceRegistrar, srv RosGrpcServer) {
	s.RegisterService(&RosGrpc_ServiceDesc, srv)
}

func _RosGrpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetRobotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetRobotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetRobotInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotCameraImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetRobotCameraImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetRobotCameraImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetRobotCameraImage(ctx, req.(*CameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotCameraImageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CameraRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RosGrpcServer).GetRobotCameraImageStream(m, &rosGrpcGetRobotCameraImageStreamServer{stream})
}

type RosGrpc_GetRobotCameraImageStreamServer interface {
	Send(*RobotCameraImage) error
	grpc.ServerStream
}

type rosGrpcGetRobotCameraImageStreamServer struct {
	grpc.ServerStream
}

func (x *rosGrpcGetRobotCameraImageStreamServer) Send(m *RobotCameraImage) error {
	return x.ServerStream.SendMsg(m)
}

func _RosGrpc_GetCurrentRobotPose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetCurrentRobotPose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetCurrentRobotPose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetCurrentRobotPose(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetCurrentRobotBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetCurrentRobotBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetCurrentRobotBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetCurrentRobotBattery(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetLatestRobotHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetLatestRobotHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetLatestRobotHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetLatestRobotHistory(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotHistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetRobotHistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetRobotHistoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetRobotHistoryList(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_NavigateToPose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigationGoal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).NavigateToPose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_NavigateToPose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).NavigateToPose(ctx, req.(*NavigationGoal))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_EmergencyStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).EmergencyStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_EmergencyStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).EmergencyStop(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_FollowWaypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaypointList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).FollowWaypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_FollowWaypoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).FollowWaypoints(ctx, req.(*WaypointList))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_SetInitialPose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotPose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).SetInitialPose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_SetInitialPose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).SetInitialPose(ctx, req.(*RobotPose))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetRobotMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetRobotMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetRobotMap(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_ControlJoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JointControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).ControlJoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_ControlJoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).ControlJoints(ctx, req.(*JointControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).GetRobotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_GetRobotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).GetRobotStatus(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_GetRobotStatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RosGrpcServer).GetRobotStatusStream(m, &rosGrpcGetRobotStatusStreamServer{stream})
}

type RosGrpc_GetRobotStatusStreamServer interface {
	Send(*RobotStatus) error
	grpc.ServerStream
}

type rosGrpcGetRobotStatusStreamServer struct {
	grpc.ServerStream
}

func (x *rosGrpcGetRobotStatusStreamServer) Send(m *RobotStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _RosGrpc_ExecuteROSCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosGrpcServer).ExecuteROSCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RosGrpc_ExecuteROSCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosGrpcServer).ExecuteROSCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RosGrpc_ExecuteROSCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RosGrpcServer).ExecuteROSCommandStream(m, &rosGrpcExecuteROSCommandStreamServer{stream})
}

type RosGrpc_ExecuteROSCommandStreamServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type rosGrpcExecuteROSCommandStreamServer struct {
	grpc.ServerStream
}

func (x *rosGrpcExecuteROSCommandStreamServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RosGrpc_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RosGrpcServer).UploadFile(&rosGrpcUploadFileServer{stream})
}

type RosGrpc_UploadFileServer interface {
	SendAndClose(*UploadFileResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type rosGrpcUploadFileServer struct {
	grpc.ServerStream
}

func (x *rosGrpcUploadFileServer) SendAndClose(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rosGrpcUploadFileServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RosGrpc_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RosGrpcServer).DownloadFile(m, &rosGrpcDownloadFileServer{stream})
}

type RosGrpc_DownloadFileServer interface {
	Send(*DownloadFileResponse) error
	grpc.ServerStream
}

type rosGrpcDownloadFileServer struct {
	grpc.ServerStream
}

func (x *rosGrpcDownloadFileServer) Send(m *DownloadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

// RosGrpc_ServiceDesc is the grpc.ServiceDesc for RosGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RosGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ros_grpc.RosGrpc",
	HandlerType: (*RosGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RosGrpc_Ping_Handler,
		},
		{
			MethodName: "GetRobotInfo",
			Handler:    _RosGrpc_GetRobotInfo_Handler,
		},
		{
			MethodName: "GetRobotCameraImage",
			Handler:    _RosGrpc_GetRobotCameraImage_Handler,
		},
		{
			MethodName: "GetCurrentRobotPose",
			Handler:    _RosGrpc_GetCurrentRobotPose_Handler,
		},
		{
			MethodName: "GetCurrentRobotBattery",
			Handler:    _RosGrpc_GetCurrentRobotBattery_Handler,
		},
		{
			MethodName: "GetLatestRobotHistory",
			Handler:    _RosGrpc_GetLatestRobotHistory_Handler,
		},
		{
			MethodName: "GetRobotHistoryList",
			Handler:    _RosGrpc_GetRobotHistoryList_Handler,
		},
		{
			MethodName: "NavigateToPose",
			Handler:    _RosGrpc_NavigateToPose_Handler,
		},
		{
			MethodName: "EmergencyStop",
			Handler:    _RosGrpc_EmergencyStop_Handler,
		},
		{
			MethodName: "FollowWaypoints",
			Handler:    _RosGrpc_FollowWaypoints_Handler,
		},
		{
			MethodName: "SetInitialPose",
			Handler:    _RosGrpc_SetInitialPose_Handler,
		},
		{
			MethodName: "GetRobotMap",
			Handler:    _RosGrpc_GetRobotMap_Handler,
		},
		{
			MethodName: "ControlJoints",
			Handler:    _RosGrpc_ControlJoints_Handler,
		},
		{
			MethodName: "GetRobotStatus",
			Handler:    _RosGrpc_GetRobotStatus_Handler,
		},
		{
			MethodName: "ExecuteROSCommand",
			Handler:    _RosGrpc_ExecuteROSCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRobotCameraImageStream",
			Handler:       _RosGrpc_GetRobotCameraImageStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRobotStatusStream",
			Handler:       _RosGrpc_GetRobotStatusStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteROSCommandStream",
			Handler:       _RosGrpc_ExecuteROSCommandStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _RosGrpc_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _RosGrpc_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "robo.proto",
}
