#!/usr/bin/env bash
# Code generated by rcf-config. DO NOT EDIT.

rcf_generated_launch_argument() {
  case "$1" in
    RC_LLM_PROVIDER) printf '%s' 'llm_provider' ;;
    RC_LLM_MODEL) printf '%s' 'llm_model' ;;
    RC_AGENT_ID) printf '%s' 'agent_id' ;;
    RC_ENABLE_RAG) printf '%s' 'enable_rag' ;;
    RC_RAG_TOP_K) printf '%s' 'rag_top_k' ;;
    RC_STRICT_CONFIG) printf '%s' 'strict_config' ;;
    RC_HTTP_PORT) printf '%s' 'http_port' ;;
    RC_HTTP_CONTROL_TOKEN) printf '%s' 'http_control_token' ;;
    ROBO_CLAW_GRPC_PORT) printf '%s' 'grpc_port' ;;
    GRPC_PEER_TOKEN) printf '%s' 'grpc_peer_token' ;;
    RC_USE_VISION) printf '%s' 'use_vision' ;;
    RC_VISION_MODEL_PATH) printf '%s' 'vision_model_path' ;;
    RC_OLLAMA_BASE_URL) printf '%s' 'llm_base_url' ;;
    RC_OLLAMA_OPTIONS_JSON) printf '%s' 'ollama_options_json' ;;
    RC_LLM_EMBEDDING_MODEL) printf '%s' 'llm_embedding_model' ;;
    RC_LLM_EMBEDDING_PROVIDER) printf '%s' 'llm_embedding_provider' ;;
    RC_LLM_EMBEDDING_BASE_URL) printf '%s' 'llm_embedding_base_url' ;;
    RC_LLM_EMBEDDING_API_KEY) printf '%s' 'llm_embedding_api_key' ;;
    RC_RAG_VECTOR_BACKEND) printf '%s' 'rag_vector_backend' ;;
    RC_RAG_SCORE_THRESHOLD) printf '%s' 'rag_score_threshold' ;;
    RC_RAG_LOCAL_MIRROR) printf '%s' 'rag_local_mirror' ;;
    QDRANT_URL) printf '%s' 'qdrant_url' ;;
    QDRANT_API_KEY) printf '%s' 'qdrant_api_key' ;;
    RC_TASK_QUEUE_MAX_SIZE) printf '%s' 'task_queue_max_size' ;;
    RC_LLM_FAIL_FAST) printf '%s' 'llm_fail_fast' ;;
    RC_ENABLE_TASK_DECOMPOSITION) printf '%s' 'enable_task_decomposition' ;;
    RC_TASK_DECOMPOSITION_MAX_STEPS) printf '%s' 'task_decomposition_max_steps' ;;
    RC_TASK_STEP_MAX_RETRIES) printf '%s' 'task_step_max_retries' ;;
    RC_HTTP_HOST) printf '%s' 'http_host' ;;
    RC_HTTP_ALLOWED_CIDRS_JSON) printf '%s' 'http_allowed_cidrs_json' ;;
    RC_HTTP_RATE_LIMIT_PER_MINUTE) printf '%s' 'http_rate_limit_per_minute' ;;
    RC_DASHBOARD_HOST) printf '%s' 'dashboard_host' ;;
    RC_DASHBOARD_PORT) printf '%s' 'dashboard_port' ;;
    ENABLE_DISCORD) printf '%s' 'enable_discord' ;;
    DISCORD_BOT_TOKEN) printf '%s' 'discord_token' ;;
    ENABLE_TELEGRAM) printf '%s' 'enable_telegram' ;;
    ENABLE_SLACK) printf '%s' 'enable_slack' ;;
    RC_ENABLE_MCP) printf '%s' 'mcp_enabled' ;;
    RC_MCP_SERVERS_JSON) printf '%s' 'mcp_servers_json' ;;
    RC_LIDAR_TOPIC) printf '%s' 'lidar_topic' ;;
    RC_IMU_TOPIC) printf '%s' 'imu_topic' ;;
    *) return 1 ;;
  esac
}
