#!/usr/bin/env python3
"""Validate the static skill catalog without importing ROS dependencies.

The runtime catalog is generated by SkillManager, but this script deliberately uses
AST so it can run in CI, on a developer machine, or inside a documentation job where
rclpy/cv_bridge are not installed.

Examples:
    python scripts/validate_skill_catalog.py
    python scripts/validate_skill_catalog.py --strict-docs
    python scripts/validate_skill_catalog.py --json
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = ROOT / "src" / "robo_claw_agent" / "robo_claw_agent" / "skills"
SKILLS_DOC = ROOT / "docs" / "SKILLS.md"


def _literal(node: ast.AST | None) -> Any:
    if node is None:
        return None
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError):
        return None


def _class_value(cls: ast.ClassDef, name: str) -> Any:
    for statement in cls.body:
        if isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return _literal(statement.value)
        elif isinstance(statement, ast.AnnAssign):
            if isinstance(statement.target, ast.Name) and statement.target.id == name:
                return _literal(statement.value)
    return None


def source_catalog() -> dict[str, dict[str, Any]]:
    catalog: dict[str, dict[str, Any]] = {}
    for path in sorted(SKILLS_ROOT.rglob("*.py")):
        if path.name == "__init__.py":
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError as exc:
            raise SystemExit(f"syntax error in {path}: {exc}") from exc
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            name = _class_value(node, "name")
            if not isinstance(name, str) or not name or name == "__mcp__":
                continue
            if name in catalog:
                previous = catalog[name]["path"]
                raise SystemExit(f"duplicate skill name {name!r}: {previous} and {path}")
            catalog[name] = {
                "name": name,
                "path": str(path.relative_to(ROOT)),
                "description": isinstance(_class_value(node, "description"), str),
                "input_schema": isinstance(_class_value(node, "input_schema"), dict),
                "risk_level": _class_value(node, "risk_level") or "action",
                "allow_with_others": _class_value(node, "allow_with_others"),
            }
    return catalog


def documented_names() -> set[str]:
    if not SKILLS_DOC.exists():
        return set()
    text = SKILLS_DOC.read_text(encoding="utf-8")
    # The catalog table is the authoritative part of SKILLS.md. Restrict parsing
    # to table rows; prose later in the guide contains parameter names and config
    # keys that are intentionally not skills (for example skill_allowed_json).
    table_text = "\n".join(line for line in text.splitlines() if "|" in line)
    return {
        match.group(1)
        for match in re.finditer(r"`([A-Za-z][A-Za-z0-9_]*)`", table_text)
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strict-docs", action="store_true", help="optional: fail when SKILLS.md is used as a complete catalog")
    parser.add_argument("--json", action="store_true", dest="as_json", help="emit machine-readable JSON")
    args = parser.parse_args()

    catalog = source_catalog()
    source_names = set(catalog)
    doc_names = documented_names()
    unknown_docs = sorted(doc_names - source_names)
    missing_docs = sorted(source_names - doc_names)
    schema_missing = sorted(name for name, item in catalog.items() if not item["input_schema"])

    report = {
        "source_skill_count": len(source_names),
        "documented_skill_count": len(doc_names & source_names),
        "unknown_documented_names": unknown_docs,
        "missing_documented_names": missing_docs,
        "missing_input_schema": schema_missing,
        "skills": sorted(catalog.values(), key=lambda item: item["name"]),
    }
    if args.as_json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(f"source skills: {report['source_skill_count']}")
        print(f"guide entries matching source skills: {report['documented_skill_count']}")
        print(f"missing input_schema: {len(schema_missing)}")
        if unknown_docs:
            print("unknown names in docs: " + ", ".join(unknown_docs))
        if missing_docs:
            print("not documented: " + ", ".join(missing_docs))

    # Unknown names in the guide are errors because they encourage LLM hallucinations.
    # Missing names are informational: SKILLS.md is a robot-specific operational
    # overlay, not a generated or exhaustive catalog.
    if unknown_docs:
        return 1
    if args.strict_docs and missing_docs:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
