package cmd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// ContractDoc represents the runtime-contract.json structure.
type ContractDoc struct {
	ContractVersion string          `json:"contract_version"`
	SchemaVersion   string          `json:"schema_version"`
	Fields          []ContractField `json:"fields"`
}

// ContractField represents each field entry in runtime-contract.json.
type ContractField struct {
	Canonical      string      `json:"canonical"`
	Type           string      `json:"type"`
	Scope          string      `json:"scope"`
	Default        interface{} `json:"default"`
	Secret         bool        `json:"secret"`
	Description    string      `json:"description"`
	Enum           []string    `json:"enum"`
	Minimum        interface{} `json:"minimum"`
	Maximum        interface{} `json:"maximum"`
	Env            string      `json:"env"`
	APIJSON        string      `json:"api_json"`
	LaunchArgument string      `json:"launch_argument"`
	ROSParameter   string      `json:"ros_parameter"`
	ValueType      string      `json:"value_type"`
	Modes          []string    `json:"modes"`
}

// LoadContractDoc loads and parses runtime-contract.json from contracts/ directory.
func LoadContractDoc(contractsDir string) (*ContractDoc, error) {
	filePath := filepath.Join(contractsDir, "runtime-contract.json")
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("runtime-contract.json 읽기 실패: %w", err)
	}

	var doc ContractDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("runtime-contract.json 파싱 실패: %w", err)
	}
	return &doc, nil
}

// RenderGoContract renders robo_claw_cli/contract/runtime_config_generated.go.
func RenderGoContract(doc *ContractDoc) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString("// Code generated by rcf-config. DO NOT EDIT.\n")
	sb.WriteString("package contract\n\n")
	sb.WriteString("type RuntimeField struct {\n")
	sb.WriteString("\tCanonical      string\n")
	sb.WriteString("\tType           string\n")
	sb.WriteString("\tScope          string\n")
	sb.WriteString("\tEnv            string\n")
	sb.WriteString("\tAPIJSON        string\n")
	sb.WriteString("\tLaunchArgument string\n")
	sb.WriteString("\tROSParameter   string\n")
	sb.WriteString("\tSecret         bool\n")
	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("const RuntimeSchemaVersion = %q\n\n", doc.SchemaVersion))
	sb.WriteString("var RuntimeFields = map[string]RuntimeField{\n")
	for _, f := range doc.Fields {
		sb.WriteString(fmt.Sprintf("\t%q: {\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("\t\tCanonical:      %q,\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("\t\tType:           %q,\n", f.Type))
		sb.WriteString(fmt.Sprintf("\t\tScope:          %q,\n", f.Scope))
		sb.WriteString(fmt.Sprintf("\t\tEnv:            %q,\n", f.Env))
		sb.WriteString(fmt.Sprintf("\t\tAPIJSON:        %q,\n", f.APIJSON))
		sb.WriteString(fmt.Sprintf("\t\tLaunchArgument: %q,\n", f.LaunchArgument))
		sb.WriteString(fmt.Sprintf("\t\tROSParameter:   %q,\n", f.ROSParameter))
		sb.WriteString(fmt.Sprintf("\t\tSecret:         %t,\n", f.Secret))
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n")
	return format.Source([]byte(sb.String()))
}

// RenderShellMapping renders scripts/generated_runtime_env.sh.
func RenderShellMapping(doc *ContractDoc) []byte {
	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Code generated by rcf-config. DO NOT EDIT.\n\n")
	sb.WriteString("rcf_generated_launch_argument() {\n")
	sb.WriteString("  case \"$1\" in\n")
	for _, f := range doc.Fields {
		if f.LaunchArgument != "" {
			sb.WriteString(fmt.Sprintf("    %s) printf '%%s' '%s' ;;\n", f.Env, f.LaunchArgument))
		}
	}
	sb.WriteString("    *) return 1 ;;\n")
	sb.WriteString("  esac\n")
	sb.WriteString("}\n")
	return []byte(sb.String())
}

// RenderPythonLaunchContract renders src/robo_claw_bringup/launch/_generated_runtime_config.py.
// The output is emitted in ruff-format-compliant style (double quotes, 4-space indent,
// multi-line dict) so that auto-formatters do not rewrite it and cause contract drift.
func RenderPythonLaunchContract(doc *ContractDoc) []byte {
	var sb strings.Builder
	sb.WriteString(`"""Code generated by rcf-config. DO NOT EDIT."""` + "\n\n")
	sb.WriteString(fmt.Sprintf("SCHEMA_VERSION = %q\n", doc.SchemaVersion))
	sb.WriteString("RUNTIME_CONFIG_FIELDS = {\n")
	for _, f := range doc.Fields {
		secretStr := "False"
		if f.Secret {
			secretStr = "True"
		}
		sb.WriteString(fmt.Sprintf("    %q: {\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("        \"env\": %q,\n", f.Env))
		sb.WriteString(fmt.Sprintf("        \"launch_argument\": %q,\n", f.LaunchArgument))
		sb.WriteString(fmt.Sprintf("        \"parameter\": %q,\n", f.ROSParameter))
		sb.WriteString(fmt.Sprintf("        \"scope\": %q,\n", f.Scope))
		sb.WriteString(fmt.Sprintf("        \"secret\": %s,\n", secretStr))
		sb.WriteString("    },\n")
	}
	sb.WriteString("}\n")
	sb.WriteString("ENV_TO_LAUNCH_ARGUMENT = {\n")
	for _, f := range doc.Fields {
		if f.LaunchArgument == "" {
			continue
		}
		sb.WriteString(fmt.Sprintf("    %q: %q,\n", f.Env, f.LaunchArgument))
	}
	sb.WriteString("}\n")
	return []byte(sb.String())
}

// RenderJSONSchema renders config-schema/generated/runtime-config.schema.json preserving field order.
func RenderJSONSchema(doc *ContractDoc) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n")
	sb.WriteString("  \"$id\": \"https://robo-claw/config-schema/runtime-config.schema.json\",\n")
	sb.WriteString("  \"title\": \"RoboClaw Runtime Configuration\",\n")
	sb.WriteString("  \"type\": \"object\",\n")
	sb.WriteString(fmt.Sprintf("  \"x-schema-version\": %q,\n", doc.SchemaVersion))
	sb.WriteString("  \"required\": [\n")
	sb.WriteString("    \"schema_version\",\n")
	sb.WriteString("    \"config_revision\",\n")
	sb.WriteString("    \"robot_name\",\n")
	sb.WriteString("    \"environment\",\n")
	sb.WriteString("    \"config\"\n")
	sb.WriteString("  ],\n")
	sb.WriteString("  \"properties\": {\n")
	sb.WriteString("    \"schema_version\": {\n")
	sb.WriteString(fmt.Sprintf("      \"const\": %q\n", doc.SchemaVersion))
	sb.WriteString("    },\n")
	sb.WriteString("    \"config_revision\": {\n")
	sb.WriteString("      \"type\": \"string\",\n")
	sb.WriteString("      \"minLength\": 1\n")
	sb.WriteString("    },\n")
	sb.WriteString("    \"robot_name\": {\n")
	sb.WriteString("      \"type\": \"string\",\n")
	sb.WriteString("      \"minLength\": 1\n")
	sb.WriteString("    },\n")
	sb.WriteString("    \"environment\": {\n")
	sb.WriteString("      \"type\": \"string\",\n")
	sb.WriteString("      \"minLength\": 1\n")
	sb.WriteString("    },\n")
	sb.WriteString("    \"config\": {\n")
	sb.WriteString("      \"type\": \"object\",\n")
	sb.WriteString("      \"properties\": {\n")

	for i, f := range doc.Fields {
		sb.WriteString(fmt.Sprintf("        %q: {\n", f.APIJSON))
		sb.WriteString(fmt.Sprintf("          \"type\": %q,\n", jsonType(f.Type)))
		sb.WriteString(fmt.Sprintf("          \"description\": %q,\n", f.Description))
		if f.Secret {
			sb.WriteString("          \"default\": null,\n")
		} else {
			defBytes, _ := json.Marshal(f.Default)
			sb.WriteString(fmt.Sprintf("          \"default\": %s,\n", string(defBytes)))
		}
		sb.WriteString(fmt.Sprintf("          \"x-canonical-name\": %q,\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("          \"x-scope\": %q,\n", f.Scope))
		sb.WriteString(fmt.Sprintf("          \"x-secret\": %t", f.Secret))

		if len(f.Enum) > 0 {
			enumBytes, _ := json.Marshal(f.Enum)
			sb.WriteString(fmt.Sprintf(",\n          \"enum\": %s", string(enumBytes)))
		}
		if f.Minimum != nil {
			minBytes, _ := json.Marshal(f.Minimum)
			sb.WriteString(fmt.Sprintf(",\n          \"minimum\": %s", string(minBytes)))
		}
		if f.Maximum != nil {
			maxBytes, _ := json.Marshal(f.Maximum)
			sb.WriteString(fmt.Sprintf(",\n          \"maximum\": %s", string(maxBytes)))
		}
		if f.Secret {
			sb.WriteString(",\n          \"writeOnly\": true")
		}
		sb.WriteString("\n        }")
		if i < len(doc.Fields)-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	sb.WriteString("      },\n")
	sb.WriteString("      \"additionalProperties\": true\n")
	sb.WriteString("    }\n")
	sb.WriteString("  },\n")
	sb.WriteString("  \"additionalProperties\": true\n")
	sb.WriteString("}\n")

	// Verify it's valid JSON
	var js map[string]interface{}
	if err := json.Unmarshal([]byte(sb.String()), &js); err != nil {
		return nil, fmt.Errorf("JSON Schema 유효성 실패: %w", err)
	}

	return []byte(sb.String()), nil
}

// RenderContractJSON renders config-schema/generated/runtime-contract.json preserving field order.
func RenderContractJSON(doc *ContractDoc) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString(fmt.Sprintf("  \"schema_version\": %q,\n", doc.SchemaVersion))
	sb.WriteString("  \"fields\": {\n")

	for i, f := range doc.Fields {
		modesBytes, _ := json.Marshal(f.Modes)
		// Format modes with space after comma if needed: ["a", "b"] -> json.Marshal produces ["a","b"]
		var modesFormatted bytes.Buffer
		_ = json.Indent(&modesFormatted, modesBytes, "        ", "  ")

		sb.WriteString(fmt.Sprintf("    %q: {\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("      \"type\": %q,\n", f.Type))
		sb.WriteString(fmt.Sprintf("      \"scope\": %q,\n", f.Scope))
		sb.WriteString(fmt.Sprintf("      \"secret\": %t,\n", f.Secret))
		sb.WriteString(fmt.Sprintf("      \"env\": %q,\n", f.Env))
		sb.WriteString(fmt.Sprintf("      \"api_json\": %q,\n", f.APIJSON))
		sb.WriteString(fmt.Sprintf("      \"launch_argument\": %q,\n", f.LaunchArgument))
		sb.WriteString(fmt.Sprintf("      \"ros_parameter\": %q,\n", f.ROSParameter))
		sb.WriteString(fmt.Sprintf("      \"modes\": %s\n", modesFormatted.String()))
		if i < len(doc.Fields)-1 {
			sb.WriteString("    },\n")
		} else {
			sb.WriteString("    }\n")
		}
	}
	sb.WriteString("  }\n}\n")

	return []byte(sb.String()), nil
}

// RenderReferenceMD renders config-schema/generated/CONFIG_REFERENCE.md.
func RenderReferenceMD(doc *ContractDoc) []byte {
	var sb strings.Builder
	sb.WriteString("# Generated RoboClaw Configuration Reference\n\n")
	sb.WriteString("> Generated by `rcf-config generate`. Do not edit this file manually.\n\n")
	sb.WriteString(fmt.Sprintf("Schema version: `%s`\n\n", doc.SchemaVersion))
	sb.WriteString("| Canonical | Env | API | Type | Default | Scope | Secret | Modes |\n")
	sb.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")

	for _, f := range doc.Fields {
		defaultVal := "masked"
		if !f.Secret {
			if f.Default == nil {
				defaultVal = ""
			} else if b, ok := f.Default.(bool); ok {
				if b {
					defaultVal = "True"
				} else {
					defaultVal = "False"
				}
			} else {
				defaultVal = fmt.Sprintf("%v", f.Default)
			}
		}
		modes := strings.Join(f.Modes, ", ")
		secretStr := fmt.Sprintf("%t", f.Secret)
		sb.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | %s |\n",
			f.Canonical, f.Env, f.APIJSON, f.Type, defaultVal, f.Scope, secretStr, modes))
	}

	sb.WriteString("\n## Descriptions\n\n")
	for _, f := range doc.Fields {
		sb.WriteString(fmt.Sprintf("### `%s`\n\n", f.Canonical))
		sb.WriteString(fmt.Sprintf("%s\n\n", f.Description))
	}

	return []byte(strings.TrimRight(sb.String(), "\n") + "\n")
}

func jsonType(t string) string {
	switch t {
	case "string", "path":
		return "string"
	case "boolean":
		return "boolean"
	case "integer":
		return "integer"
	case "number":
		return "number"
	case "array":
		return "array"
	case "object":
		return "object"
	default:
		return t
	}
}

// GenerateArtifacts writes or verifies generated artifacts from contracts/runtime-contract.json.
// If check is true, it only verifies if the on-disk files match without modifying them.
func GenerateArtifacts(root string, check bool) ([]string, error) {
	doc, err := LoadContractDoc(filepath.Join(root, "contracts"))
	if err != nil {
		return nil, err
	}

	goCode, err := RenderGoContract(doc)
	if err != nil {
		return nil, fmt.Errorf("Go 계약 코드 렌더링 실패: %w", err)
	}

	shellCode := RenderShellMapping(doc)
	pyCode := RenderPythonLaunchContract(doc)

	jsonSchema, err := RenderJSONSchema(doc)
	if err != nil {
		return nil, fmt.Errorf("JSON Schema 렌더링 실패: %w", err)
	}

	contractJSON, err := RenderContractJSON(doc)
	if err != nil {
		return nil, fmt.Errorf("Contract JSON 렌더링 실패: %w", err)
	}

	refMD := RenderReferenceMD(doc)

	targets := map[string][]byte{
		filepath.Join(root, "robo_claw_cli", "contract", "runtime_config_generated.go"):           goCode,
		filepath.Join(root, "scripts", "generated_runtime_env.sh"):                                shellCode,
		filepath.Join(root, "src", "robo_claw_bringup", "launch", "_generated_runtime_config.py"): pyCode,
		filepath.Join(root, "config-schema", "generated", "runtime-config.schema.json"):           jsonSchema,
		filepath.Join(root, "config-schema", "generated", "runtime-contract.json"):                contractJSON,
		filepath.Join(root, "config-schema", "generated", "CONFIG_REFERENCE.md"):                  refMD,
	}

	var changed []string
	for path, content := range targets {
		existing, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(existing, content) {
			rel, relErr := filepath.Rel(root, path)
			if relErr != nil {
				rel = path
			}
			changed = append(changed, rel)

			if !check {
				if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
					return nil, err
				}
				if err := os.WriteFile(path, content, 0644); err != nil {
					return nil, err
				}
			}
		}
	}

	return changed, nil
}
